### ISSUE TITLE
After 1-setup.sh nova-scheduler and nova-compute services go down

### ISSUE THREAD

**Issue by celttechie** [cyx1231st/nova-scheduler-bench#1]
I spun up a new Ubuntu 14.04 VM and cloned devstack to /home/stack and fired it up.  Then I cloned nova-scheduler-bench to /home/stack and symlinked /opt/devstack to /home/stack/devstack.  Ran 0-prepare.sh, then "./1-setup.sh 3 10 1".  Both complete with no errors, but then after a few minutes nova service-list shows:

stack@devstack1:~/nova-scheduler-bench$ nova service-list
+----+------------------+-----------+----------+---------+-------+----------------------------+-----------------+
| Id | Binary           | Host      | Zone     | Status  | State | Updated_at                 | Disabled Reason |
+----+------------------+-----------+----------+---------+-------+----------------------------+-----------------+
| 4  | nova-conductor   | devstack1 | internal | enabled | up    | 2016-05-21T20:23:25.000000 | -               |
| 5  | nova-network     | devstack1 | internal | enabled | up    | 2016-05-21T20:23:23.000000 | -               |
| 6  | nova-scheduler   | devstack1 | internal | enabled | down  | 2016-05-21T19:54:45.000000 | -               |
| 7  | nova-consoleauth | devstack1 | internal | enabled | up    | 2016-05-21T20:23:23.000000 | -               |
| 8  | nova-compute     | devstack1 | nova     | enabled | down  | 2016-05-21T19:54:48.000000 | -               |
+----+------------------+-----------+----------+---------+-------+----------------------------+-----------------+

Please advise, I'd really like to take this through it's paces.

**Comment by cyx1231st** [comment]
Hi! It seems all the patched services are not launched properly in your environment. That may be caused by an incompatible version of OpenStack prior to Mitaka release.  So what's your OpenStack version?

To debug and get error messages, you can try:
$ cd ~/nova-scheduler-bench/openstack-bench/
$ python run_bench.py --console --debug conductor

The coloured logs will be printed to the console, it can help me to identify the problem.

**Comment by EdLeafe** [comment]
Hi! I'm running devstack with current OpenStack master. I'm seeing the n-* services also being terminated after running 1-setup.sh. When I restart them all and continue with 2-create.sh, I get the following traceback:

```
Sent a request p18 with flavor 155
http://localhost:8774/v2.1/aa2003169ace46cba0177286cbc08685/servers -X POST -H "X-Auth-Project-Id: admin" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: " -d '{"server": {"name": "p'19'", "imageRef": "''", "flavorRef": "'151'", "max_count": 1, "min_count": 1}}'
Sent a request p19 with flavor 151
Traceback (most recent call last):
  File "parse.py", line 4, in <module>
    parse.main1()
  File "/home/stack/nova-scheduler-bench/openstack_bench/log_parser/parse.py", line 1194, in main1
    log_collector = LogCollector(args.folder, driver_obj)
  File "/home/stack/nova-scheduler-bench/openstack_bench/log_parser/log_parser.py", line 315, in __init__
    self.service_host_dict.keys()))
RuntimeError: Incompatible log files, expected set(['api', 'compute', 'conductor', 'scheduler']), but [].
Done, requested 20 instances!
```
There are no files created in either results/ or runtime_logs/.

I ran the debug statement in your reply above, and pasted the output here: http://paste.openstack.org/show/607488/

Sorry, no output color :)

Can you please give me further debugging direction?

**Comment by EdLeafe** [comment]
OK, looking through the code, I see that it is deliberate that the devstack services are stopped so that the patched services can be run instead. However, I'm not seeing these services running.

**Comment by cyx1231st** [comment]
Hi, Ed! Sorry for the late reply.

This codebase hasn't been updated for 5 months (quite a while!). It is very likely to break due to the later development of devstack/OpenStack. I recommend to try the devstack/OpenStack versions 5 months ago if you need a demo immediately.

I still need some time to finish some other works for now, e.g. https://github.com/cyx1231st/workflow_parser which is an generalized and independent log parser. I'll plug it to this repo after the work is done. And make it workable again.

If you have other requirements, please tell me, thank you!

**Comment by EdLeafe** [comment]
I tried re-installing this with devstack and nova from 6 months ago, but got the same failures.

Please let me know when this is ready again.

**Comment by cyx1231st** [comment]
Interesting.. OK!

**Comment by MohammedMoin** [comment]
Hi...
Can i use this bench for multinode setup for Newton release.

**Comment by orperes1** [comment]
Hi,
i have the same problems as Edleafe describe do you find sulotion?

**Comment by cyx1231st** [comment]
The code won't work because the analysis is deeply coupled with Nova internal implementations( https://github.com/cyx1231st/nova-scheduler-bench/blob/master/openstack_bench/os_patcher/patchers/nova_patcher.py) several years ago. But it's inevitable because tracepoints just work this way. So currently this repo is only for idea demonstration.
